[package]
name = "jwt-rust"
version = "1.0.0-alpha.1"
authors = ["Robert Bragg <robert@sixbynine.org>"]
license = "MIT"
description = "A Json Web Token implementation for Rust"
homepage = "https://github.com/rib/jwt-rust"
repository = "https://github.com/rib/jwt-rust"
keywords = ["jwt", "web", "api", "token"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11"
serde = { version="1", features=["derive"] }
serde_json = "1"
regex = "1"
pem = "0.7"
simple_asn1 = "0.4"
ring = { version = "0.16", features = ["std"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["test-util", "rt-core", "macros"] }
tokio-test = "0.2"