[package]
name = "jwt-rust"
version = "0.1.0"
authors = ["Robert Bragg <robert@sixbynine.org>"]
license = "MIT"
description = "A Json Web Token implementation for Rust"
keywords = ["jwt", "web", "api", "token"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11"
serde = { version="1.0.102", features=["derive"] }
serde_json = "1.0.42"
regex = "1.3.1"
pem = "0.7"
simple_asn1 = "0.4"
ring = { version = "0.16.5", features = ["std"] }

[dev-dependencies]
tokio = { version = "0.2.1", features = ["test-util", "rt-core", "macros"] }
tokio-test = "0.2.0"